<a href="https://colab.research.google.com/github/Tomaszlek/Data_Science_kursy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy**

In [2]:
import numpy as np

np.__version__

'1.25.2'

In [9]:
x = np.array([1, 2, 3])
print(x)

nowa_tablica = np.array([[2, 4], [1, 2+0.5j]], dtype=complex)
print(nowa_tablica)

x.ndim
x.size
x.shape
x.dtype


nowa_tablica.shape

[1 2 3]
[[2.+0.j  4.+0.j ]
 [1.+0.j  2.+0.5j]]


(2, 2)

In [3]:
tablica = np.array([1, 5.5, 23], dtype=float)

In [18]:
x = np.zeros(shape = (4, 10), dtype = np.uint8)
print(x)

y = np.ones(shape = (3, 5, 2), dtype = np.uint8)
print(y)

z = np.full(shape = (3, 3), fill_value = 4, dtype = int)
print(z)

w = np.arange(start = 10, stop = 1, step = -1)
print(w)

liniowa = np.linspace(start = 0, stop = 64, num = 10, dtype = int)
print(liniowa)
liniowa.reshape((2, -1))

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[[1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]]]
[[4 4 4]
 [4 4 4]
 [4 4 4]]
[10  9  8  7  6  5  4  3  2]
[ 0  7 14 21 28 35 42 49 56 64]


array([[ 0,  7, 14, 21, 28],
       [35, 42, 49, 56, 64]])

##Operacje na tablicach

In [26]:
tablica1 = np.array([4, 2, 5, 3])
tablica2 = np.array([7, 4, 6, 1])

print(tablica1, tablica2)
np.add(tablica1, tablica2)
np.subtract(tablica1, tablica2)
np.multiply(tablica1, tablica2)
np.divide(tablica1, tablica2)

tablica1 + 3

tablica1.reshape((2,2))
tablica2.reshape((2,2))

print(np.dot(tablica1, tablica2))
print(np.dot(tablica2, tablica1))

[4 2 5 3] [7 4 6 1]
69
69


Liczby pseudolosowe

In [38]:
np.random.seed(0)

np.random.randn(20, 2)
np.random.rand(2, 4)*100
np.random.randint(low = 10, high = 100, size=(2, 10))

np.random.choice(tablica2)

np.random.shuffle(tablica1)
print(tablica1)

[3 4 5 2]


Funkcje matematyczne

In [46]:
np.exp(tablica1)
np.sqrt(tablica1)

np.all(tablica1) #sprawdza, czy wszystkie wartości zwrócą nam prawdę
np.any(tablica1) #tu tak samo, tylko gdy jakakolwiek wartość to prawda

np.argmax(tablica1)
tablica1[np.argmax(tablica1)]
tablica2[np.argmin(tablica2)]

np.argsort(tablica1)

np.median(tablica1)
np.std(tablica2)

2.29128784747792

Indeksacja, wycinanie

In [52]:
tab = np.arange(20)

print(tab[2:])

tab = tab.reshape((4, 5))

print(tab[:, -1])

print(tab[1:3, 2:4])
tab[1, 4] = 19

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 4  9 14 19]
[[ 7  8]
 [12 13]]


# Iterowanie po tablicy, filtrowanie

In [61]:
for rzad in tab.flat:
  print(rzad)

tab.ravel()
tab.T

print(tab[np.bitwise_and(tab > 10, tab < 15)])
print(tab[np.bitwise_or(tab < 10, tab > 16)]) #kiedy duzo warunkow, uzywamy bitwise_and, bitwise_or lub bitwise_not

0
1
2
3
4
5
6
7
8
19
10
11
12
13
14
15
16
17
18
19
[11 12 13 14]
[ 0  1  2  3  4  5  6  7  8 19 17 18 19]


# Algebra liniowa
## wektory i macierze

In [3]:
wektor1 = np.array([3, 1])
wektor2 = np.array([4, 2])

print(np.linalg.norm(wektor1 - wektor2))

1.4142135623730951


In [10]:
macierz1 = np.array([[3, 1], [-5, 2]])
macierz2 = np.array([[5], [3]])

macierz3 = np.dot(macierz1, macierz2)
print(macierz3)

wyznacznik1 = np.linalg.det(macierz1)
print(wyznacznik1)

macierz_jednostkowa = np.eye(4, dtype = int)
print(macierz_jednostkowa)

macierz_odwrotna = np.linalg.inv(macierz1)
print(macierz_odwrotna)

macierz_transponowana = np.transpose(macierz3)
print(macierz_transponowana)

[[ 18]
 [-19]]
11.000000000000002
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[ 0.18181818 -0.09090909]
 [ 0.45454545  0.27272727]]
[[ 18 -19]]


# Funkcje statystyczne

In [13]:
ceny = np.array([[12, 16, 15, 14, 2000],
                 [13, 18, 13, 14.3, 1230],
                 [11, 12, 15.6, 14.5, 2340]])

suma = ceny.sum(axis = 1) #sumowanie po kolumnach, axis = 0, wiersze to axis = 1
print(suma)

print(np.min(ceny))
print(np.max(ceny))
print(np.median(ceny))
print(np.std(ceny))
print(np.var(ceny))

[2057.  1288.3 2393.1]
11.0
2340.0
14.5
765.7512126881245
586374.9197333333
